apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 49.0.0 # Check the latest version if needed
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  values:
    prometheus:
      serviceMonitorSelectorNilUsesHelmValues: false
    grafana:
      adminPassword: "admin" # Set your preferred password