apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../my-cluster/monitoring/prometheus-helmrelease.yaml
- ../../my-cluster/monitoring/prometheus-helmrepo.yaml
